// client/vue/src/components/AddBook.vue
<template>
  <div class="AddBook">
    <div class="BookFrom">
      <h2>Add New Book</h2>
      <input 
          ref="bookname"
          type="text" 
          placeholder="Name" 
          v-model="book.name" />
      <textarea 
          type="text" 
          rows="3"
          placeholder="Description"
          v-model="book.description" />
      <input 
          min="0"
          type="number" 
          placeholder="Count" 
          v-model="book.count" />
      <input 
          type="text" 
          placeholder="Author" 
          v-model="book.author" />
    </div>
    <button class="Btn BtnPrimary" :disabled="isDisable" @click="addBook({...book})">Add Book</button>
    <button @click="saveBooks" class="Btn BtnSuccess">Save Data</button>
    <span v-if="addErrorMessage != ''" class="Error">{{addErrorMessage}}</span>
  </div>
</template>

<script>
import * as types from '../store/types';

export default {
  name: 'AddBook',
  data(){
    return{
      book: {
        name: '',
        description: '',
        count: '',
        author: '',
      },
      addErrorMessage: '',
      isDisable: true,
    }
  },
  methods: {
    saveBooks: function(){
      this.$store.dispatch(types.ACTION_SAVE_BOOKS);
    },
    addBook: function(){
      let data = {...this.book};
      this.$store.dispatch(types.ACTION_ADD_BOOK,data).then(() => {
        this.book.name = '';
        this.book.description = '';
        this.book.count = 0;
        this.book.author = '';
        this.$refs.bookname.focus();
      }, error => {
        this.addErrorMessage = error;
      });
    }
  },
  watch:{
    book:{
      handler: function(newValue) {
        let app = this;
        if (newValue.name.trim() === "" ||
          newValue.description.trim() === "" ||
          newValue.count <= 0 ||
          newValue.author.trim() === "") {
            app.isDisable = true;
        } else {
          app.isDisable = false;
        }
      },
      deep: true
    }
  }
}
</script>

<style scoped>
</style>

// client/react/src/components/AddBook.js
import React, { Component } from 'react';

class AddBook extends Component {
    state = {
        name: '', 
        description: '',
        count: '',
        author: '',
        isDisable: true
    }

    componentWillUpdate(nextProps, nextState) {
        let app = this;
        setTimeout(function(){
            if ( app.state.name.trim() === "" || 
                app.state.description.trim() === "" || 
                app.state.author.trim() === "" ) {
                    app.setState({isDisable: true});
            } else {
                app.setState({isDisable: false});
            }
        },100);
    }

    nameChangedHandler = (event) => {
        this.setState({name: event.target.value});
    }

    descriptionChangedHandler = (event) => {
        this.setState({description: event.target.value});
    }

    countChangedHandler = (event) => {
        this.setState({count: event.target.value});
    }

    authorChangedHandler = (event) => {
        this.setState({author: event.target.value});
    }

    addBookHandler = () => {
        this.props.add(this.state.name, this.state.description, this.state.count, this.state.author)
        this.setState({
            name: '', 
            description: '',
            count: '',
            author: '',
            isDisable: true
        })
    }

    render () {
        return (
            <div className="AddBook">
                <div className="BookFrom">
                    <h2>Add New Book</h2>
                    <input 
                        type="text" 
                        placeholder="Name" 
                        onChange={this.nameChangedHandler}
                        value={this.state.name} />
                    <textarea 
                        type="text" 
                        rows="3"
                        placeholder="Description"
                        onChange={this.descriptionChangedHandler}
                        value={this.state.description} />
                    <input 
                        min="0"
                        type="number" 
                        placeholder="Count" 
                        onChange={this.countChangedHandler}
                        value={this.state.count} />
                    <input 
                        type="text" 
                        placeholder="Author" 
                        onChange={this.authorChangedHandler}
                        value={this.state.author} />
                </div>
                <button className="Btn BtnPrimary" 
                    disabled={this.state.isDisable} 
                    onClick={this.addBookHandler}>Add Book</button>
                <button className="Btn BtnSuccess" 
                    onClick={this.props.save}>Save Data</button>
            </div>
        );
    }
}

export default AddBook;
