// client/vue/src/components/Book.vue
<template>
  <div class="Book" v-if="filterByValue(book)">
    <div v-if="isEditMode">
      <input 
          type="text" 
          placeholder="Name" 
          v-model="book.name" />
      <textarea 
          type="text" 
          rows="3"
          placeholder="Description"
          v-model="book.description"/>
      <input 
          min="0"
          type="number" 
          placeholder="Count" 
          v-model="book.count"/>
      <input 
          type="text" 
          placeholder="Author" 
          v-model="book.author" />
      <button class="Btn BtnSuccess" @click="toggleEditMode()">Save</button>
    </div>
    <div v-else>
      <h2 class="Title">{{book.name}}</h2>
      <small class="OtherInfo">Author: {{book.author}}, Qty: {{book.count}}</small>
      <p :class="descriptionClass">{{book.description}}</p>
      <button class="Btn BtnDefault" @click="showMoreToggle()">Show Detail</button>
      <button class="Btn BtnInfo" @click="toggleEditMode()">Edit</button>
      <button class="Btn BtnDanger" @click="removeBook(book.id)">Remove</button>
    </div>
  </div>
</template>

<script>
import {mapActions} from 'vuex';
import * as types from '../store/types';

export default {
  name: 'Book',
  props: ['book','searchValue'],
  data(){
    return{
      isEditMode: false,
      showMore: false,
      descriptionClass: 'Description Short'
    }
  },
  methods: {
    ...mapActions({
      removeBook: types.ACTION_REMOVE_BOOK
    }),
    filterByValue: function(obj){
        if (this.searchValue.trim() === '') return true;
        return Object.keys(obj).some(k => obj[k].toString().toLowerCase().includes(this.searchValue.toLowerCase()));
    },
    showMoreToggle: function() {
      if (this.showMore !== true)
          this.descriptionClass = 'Description';
      else
          this.descriptionClass =  'Description Short'
      this.showMore = !this.showMore;
    },
    toggleEditMode: function() {
      this.isEditMode = !this.isEditMode
    }
  }
}
</script>

<style scoped>
</style>

// client/react/src/components/Book.js
import React, { Component } from 'react';

class Book extends Component {

    state = {
        isEditMode: false,
        showMore: false,
        descriptionClass: 'Description Short'
    }

    toggleEditModeHandler = (event,index) => {
        this.setState({ isEditMode: !this.state.isEditMode });
    }

    showMoreToggleHandler = () => {
        if (this.state.showMore !== true)
            this.setState({ descriptionClass: 'Description' });
        else
            this.setState({ descriptionClass: 'Description Short' });
        this.setState({ showMore: !this.state.showMore });
    }

    render () {
        return (
            <div className="Book">
                {
                    this.state.isEditMode ? 
                        <div>
                            <input 
                                type="text" 
                                placeholder="Name" 
                                onChange={this.props.nameChange}
                                value={this.props.name} />
                            <textarea 
                                type="text" 
                                rows="3"
                                placeholder="Description"
                                onChange={this.props.descriptionChange}
                                value={this.props.description} />
                            <input 
                                min="0"
                                type="number" 
                                placeholder="Count" 
                                onChange={this.props.countChange}
                                value={this.props.count} />
                            <input 
                                type="text" 
                                placeholder="Author" 
                                onChange={this.props.authorChange}
                                value={this.props.author} />
                            <button className="SaveBtn Btn BtnSuccess" onClick={() => this.toggleEditModeHandler()}>Save</button>
                        </div> :
                        <div>
                            <h2 className="Title">{this.props.name}</h2>
                            <small className="OtherInfo">Author: {this.props.author}, Qty: {this.props.count}</small>
                            <p className={this.state.descriptionClass}>{this.props.description}</p>
                            <button className="ShowMoreBtn Btn BtnDefault" onClick={() => this.showMoreToggleHandler()}>
                                { this.state.showMore ? 'Hide Detail' : 'Show Detail' }
                            </button>
                            <button className="Btn BtnInfo" onClick={() => this.toggleEditModeHandler()}>Edit</button>
                            <button className="Btn BtnDanger" onClick={this.props.remove}>Remove</button>
                        </div>
                }
            </div>
        )
    }
}

export default Book;
