// client/react/src/components/AddBook.js
import React, { Component } from 'react';

class AddBook extends Component {
    state = {
        name: '', 
        description: '',
        count: '',
        author: '',
        isDisable: true
    }

    componentWillUpdate(nextProps, nextState) {
        let app = this;
        setTimeout(function(){
            if ( app.state.name.trim() === "" || 
                app.state.description.trim() === "" || 
                app.state.author.trim() === "" ) {
                    app.setState({isDisable: true});
            } else {
                app.setState({isDisable: false});
            }
        },100);
    }

    nameChangedHandler = (event) => {
        this.setState({name: event.target.value});
    }

    descriptionChangedHandler = (event) => {
        this.setState({description: event.target.value});
    }

    countChangedHandler = (event) => {
        this.setState({count: event.target.value});
    }

    authorChangedHandler = (event) => {
        this.setState({author: event.target.value});
    }

    addBookHandler = () => {
        this.props.add(this.state.name, this.state.description, this.state.count, this.state.author)
        this.setState({
            name: '', 
            description: '',
            count: '',
            author: '',
            isDisable: true
        })
    }

    render () {
        return (
            <div className="AddBook">
                <div className="BookFrom">
                    <h2>Add New Book</h2>
                    <input 
                        type="text" 
                        placeholder="Name" 
                        onChange={this.nameChangedHandler}
                        value={this.state.name} />
                    <textarea 
                        type="text" 
                        rows="3"
                        placeholder="Description"
                        onChange={this.descriptionChangedHandler}
                        value={this.state.description} />
                    <input 
                        min="0"
                        type="number" 
                        placeholder="Count" 
                        onChange={this.countChangedHandler}
                        value={this.state.count} />
                    <input 
                        type="text" 
                        placeholder="Author" 
                        onChange={this.authorChangedHandler}
                        value={this.state.author} />
                </div>
                <button className="Btn BtnPrimary" 
                    disabled={this.state.isDisable} 
                    onClick={this.addBookHandler}>Add Book</button>
                <button className="Btn BtnSuccess" 
                    onClick={this.props.save}>Save Data</button>
            </div>
        );
    }
}

export default AddBook;

// client/angular/src/app/books/add-book/add-book.component.ts
import { Component, OnInit, ViewChild, ElementRef, Output, EventEmitter } from '@angular/core';
import { BooksService } from 'src/app/shared/books.service';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-add-book',
  templateUrl: './add-book.component.html',
  styleUrls: ['./add-book.component.sass']
})
export class AddBookComponent implements OnInit {
  @ViewChild('nameInput') nameInputRef: ElementRef;
  @Output() saveDataMessage: EventEmitter<string> = new EventEmitter<string>();

  name: string = "";
  description: string = "";
  count: number = null;
  author: string = "";
  isDisabled: boolean = true;
  
  constructor(private bookService: BooksService) { }

  ngOnInit() { }

  resetAddBookForm(){
    this.name = "";
    this.description = "";
    this.count = null;
    this.author = "";
    this.isDisabled = true;
    this.nameInputRef.nativeElement.focus();
  }

  onAddBook(){
    this.bookService.addBook(this.name,this.description,this.count,this.author);
    this.resetAddBookForm();
  }

  onSaveBook(){
    if(!environment.production){
      this.saveDataMessage.emit('You are running development environment so you can not save data!');
    } else {
      this.bookService.saveBooks().subscribe(data => {
        this.saveDataMessage.emit(data.message);
      });
    }
  }

  onChange(){
    const app = this;
    setTimeout( function(){
      if(
        app.name.trim() !== "" &&
        app.description.trim() !== "" &&
        app.count > 0 &&
        app.author.trim() !== ""
      ) {
        app.isDisabled = false;
      } else {
        app.isDisabled = true;
      }
    },100);
  }

}
<div class="AddBook">
    <div class="BookFrom">
        <h2>Add New Book</h2>
        <input 
            #nameInput
            type="text" 
            placeholder="Name" 
            (ngModelChange)="onChange()"
            [(ngModel)]="name"/>
        <textarea 
            type="text" 
            rows="3"
            placeholder="Description"
            (ngModelChange)="onChange()"
            [(ngModel)]="description"></textarea>
        <input 
            min="0"
            type="number" 
            placeholder="Count" 
            (ngModelChange)="onChange()"
            [(ngModel)]="count"/>
        <input 
            type="text" 
            placeholder="Author" 
            (ngModelChange)="onChange()"
            [(ngModel)]="author"/>
    </div>
    <button class="Btn BtnPrimary" [disabled]="isDisabled" (click)="onAddBook()">Add Book</button>
    <button class="Btn BtnSuccess" (click)="onSaveBook()">Save Data</button>
</div>
