// client/react/src/components/Book.js
import React, { Component } from 'react';

class Book extends Component {

    state = {
        isEditMode: false,
        showMore: false,
        descriptionClass: 'Description Short'
    }

    toggleEditModeHandler = (event,index) => {
        this.setState({ isEditMode: !this.state.isEditMode });
    }

    showMoreToggleHandler = () => {
        if (this.state.showMore !== true)
            this.setState({ descriptionClass: 'Description' });
        else
            this.setState({ descriptionClass: 'Description Short' });
        this.setState({ showMore: !this.state.showMore });
    }

    render () {
        return (
            <div className="Book">
                {
                    this.state.isEditMode ? 
                        <div>
                            <input 
                                type="text" 
                                placeholder="Name" 
                                onChange={this.props.nameChange}
                                value={this.props.name} />
                            <textarea 
                                type="text" 
                                rows="3"
                                placeholder="Description"
                                onChange={this.props.descriptionChange}
                                value={this.props.description} />
                            <input 
                                min="0"
                                type="number" 
                                placeholder="Count" 
                                onChange={this.props.countChange}
                                value={this.props.count} />
                            <input 
                                type="text" 
                                placeholder="Author" 
                                onChange={this.props.authorChange}
                                value={this.props.author} />
                            <button className="SaveBtn Btn BtnSuccess" onClick={() => this.toggleEditModeHandler()}>Save</button>
                        </div> :
                        <div>
                            <h2 className="Title">{this.props.name}</h2>
                            <small className="OtherInfo">Author: {this.props.author}, Qty: {this.props.count}</small>
                            <p className={this.state.descriptionClass}>{this.props.description}</p>
                            <button className="ShowMoreBtn Btn BtnDefault" onClick={() => this.showMoreToggleHandler()}>
                                { this.state.showMore ? 'Hide Detail' : 'Show Detail' }
                            </button>
                            <button className="Btn BtnInfo" onClick={() => this.toggleEditModeHandler()}>Edit</button>
                            <button className="Btn BtnDanger" onClick={this.props.remove}>Remove</button>
                        </div>
                }
            </div>
        )
    }
}

export default Book;

// client/angular/src/app/books/book/book.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Book } from 'src/app/shared/book.model';
import { BooksService } from '../../shared/books.service';

@Component({
  selector: 'app-book',
  templateUrl: './book.component.html',
  styleUrls: ['./book.component.sass']
})
export class BookComponent implements OnInit {
  @Input() book: Book;
  @Input() index: number;
  isEditMode: boolean = false;
  showMore: boolean = false;

  constructor(private booksService: BooksService) { }

  ngOnInit() {
  }

  onToggleEditMode(){
    this.isEditMode = !this.isEditMode;
  }

  onToggleShowDetail(){
    this.showMore = !this.showMore;
  }

  onRemoveBook(){
    this.booksService.removeBook(this.book.id);
  }

}

<div *ngIf="isEditMode; else elseBlock">
    <input 
        type="text" 
        placeholder="Name" 
        [(ngModel)]="book.name"/>
    <textarea 
        type="text" 
        rows="3"
        placeholder="Description"
        [(ngModel)]="book.description"></textarea>
    <input 
        min="0"
        type="number" 
        placeholder="Count" 
        [(ngModel)]="book.count" />
    <input 
        type="text" 
        placeholder="Author" 
        [(ngModel)]="book.author"/>
    <button class="SaveBtn Btn BtnSuccess" (click)="onToggleEditMode()">Save</button>
</div>
<ng-template #elseBlock>
    <div>
        <h2 class="Title">{{book.name}}</h2>
        <small class="OtherInfo">Author: {{book.author}}, Qty: {{book.count}}</small>
        <p [class]="showMore ? 'Description' : 'Description Short'">{{book.description}}</p>
        <button class="ShowMoreBtn Btn BtnDefault" (click)="onToggleShowDetail()">
            {{showMore ? 'Hide Detail' : 'Show Detail'}}
        </button>
        <button class="Btn BtnInfo" (click)="onToggleEditMode()">Edit</button>
        <button class="Btn BtnDanger" (click)="onRemoveBook()">Remove</button>
    </div>
</ng-template>
